
var GOOGLE_CLIENT_ID = '654321';
var GOOGLE_SECRET_KEY = '54321';
var GOOGLE_CALLBACK_URL = '/api/users/google/callback';
var FACEBOOK_APP_ID = '12345';
var FACEBOOK_SECRET_KEY = '1234';
var FACEBOOK_CALLBACK_URL = '/api/users/facebook/callback';
var DEV_DOMAIN = 'https://code_lab_by_shail.herokuapp.com/';
var TOKEN_SECRET = 'awesomeshail';
//for Dev and production
//var MONGO_DB_URI='mongodb://localhost:27017/myproject';
var MONGO_DB_URI='mongodb://localhost';

var RESET_TOKEN_IN_HOURS = 6;

var GMAIL_SMTP_EMAIL_ID = 'shailendra.bitspilani@gmail.com';
var GMAIL_SMTP_PASSWORD = 'somepassword';


module.exports =
{
	GOOGLE_AUTH: {
		GOOGLE_CLIENT_ID : GOOGLE_CLIENT_ID,
		GOOGLE_SECRET_KEY : GOOGLE_SECRET_KEY,
		GOOGLE_CALLBACK_URL : GOOGLE_CALLBACK_URL
	},
	FACEBOOK_AUTH: {
		FACEBOOK_CLIENT_ID : FACEBOOK_APP_ID,
		FACEBOOK_SECRET_KEY : FACEBOOK_SECRET_KEY,
		FACEBOOK_CALLBACK_URL: FACEBOOK_CALLBACK_URL
	},
	GMAIL_SMTP: {
		GMAIL_SMTP_EMAIL_ID : GMAIL_SMTP_EMAIL_ID,
		GMAIL_SMTP_PASSWORD : GMAIL_SMTP_PASSWORD
	},
	DEV_DOMAIN : DEV_DOMAIN,
	TOKEN_SECRET: TOKEN_SECRET,
	MONGO_DB_URI: MONGO_DB_URI,
	RESET_TOKEN_IN_HOURS: RESET_TOKEN_IN_HOURS,
	IS_AUTHENTICATION_DISABLED_FOR_REST_API_TESTING: true
};
